#!/usr/bin/env python3

from charms.reactive import remove_state
from charmhelpers.core import hookenv
import sys
sys.path.append('lib')
sys.path.append('reactive')

from plex import install_plex

remove_state('plex.installed')
hookenv.log('Running install to check for new versions','INFO')
install_plex()

