#!/usr/bin/env python3

from charms.reactive import remove_state
import sys
sys.path.append('lib')
sys.path.append('reactive')

from plex import install_plex

remove_state('plex.installed')
install_plex()

